name: autotest.yml
on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - reopened
  push:
    branches:
      - dev
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: Set up JDK 21 for x64
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'microsoft'
            architecture: x64
        - name: test
          run:
            mvn test

